INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'Las Condes',N'RM',N'Chile'),
	 (N'Viña del Mar',N'Valparaíso',N'Chile'),
	 (N'ALGARROBO',NULL,N'Chile'),
	 (N'ALHUE',NULL,N'Chile'),
	 (N'ALTO BIOBIO',NULL,N'Chile'),
	 (N'ALTO DEL CARMEN',NULL,N'Chile'),
	 (N'ALTO HOSPICIO',NULL,N'Chile'),
	 (N'ANCUD',NULL,N'Chile'),
	 (N'ANDACOLLO',NULL,N'Chile'),
	 (N'ANGOL',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'ANTOFAGASTA',NULL,N'Chile'),
	 (N'ANTUCO',NULL,N'Chile'),
	 (N'ARAUCO',NULL,N'Chile'),
	 (N'ARICA',NULL,N'Chile'),
	 (N'AYSEN',NULL,N'Chile'),
	 (N'BUIN',NULL,N'Chile'),
	 (N'BULNES',NULL,N'Chile'),
	 (N'CABILDO',NULL,N'Chile'),
	 (N'CABO DE HORNOS',NULL,N'Chile'),
	 (N'CABRERO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'CALAMA',NULL,N'Chile'),
	 (N'CALBUCO',NULL,N'Chile'),
	 (N'CALDERA',NULL,N'Chile'),
	 (N'CALERA DE TANGO',NULL,N'Chile'),
	 (N'CALLE LARGA',NULL,N'Chile'),
	 (N'CAMARONES',NULL,N'Chile'),
	 (N'CAMINA',NULL,N'Chile'),
	 (N'CANELA',NULL,N'Chile'),
	 (N'CANETE',NULL,N'Chile'),
	 (N'CARAHUE',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'CARTAGENA',NULL,N'Chile'),
	 (N'CASABLANCA',NULL,N'Chile'),
	 (N'CASTRO',NULL,N'Chile'),
	 (N'CATEMU',NULL,N'Chile'),
	 (N'CAUQUENES',NULL,N'Chile'),
	 (N'CERRILLOS',NULL,N'Chile'),
	 (N'CERRO NAVIA',NULL,N'Chile'),
	 (N'CHAITEN',NULL,N'Chile'),
	 (N'CHANARAL',NULL,N'Chile'),
	 (N'CHANCO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'CHEPICA',NULL,N'Chile'),
	 (N'CHIGUAYANTE',NULL,N'Chile'),
	 (N'CHILE CHICO',NULL,N'Chile'),
	 (N'CHILLAN',NULL,N'Chile'),
	 (N'CHILLAN VIEJO',NULL,N'Chile'),
	 (N'CHIMBARONGO',NULL,N'Chile'),
	 (N'CHOLCHOL',NULL,N'Chile'),
	 (N'CHONCHI',NULL,N'Chile'),
	 (N'CISNES',NULL,N'Chile'),
	 (N'COBQUECURA',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'COCHAMO',NULL,N'Chile'),
	 (N'COCHRANE',NULL,N'Chile'),
	 (N'CODEGUA',NULL,N'Chile'),
	 (N'COELEMU',NULL,N'Chile'),
	 (N'COIHUECO',NULL,N'Chile'),
	 (N'COINCO',NULL,N'Chile'),
	 (N'COLBUN',NULL,N'Chile'),
	 (N'COLCHANE',NULL,N'Chile'),
	 (N'COLINA',NULL,N'Chile'),
	 (N'COLLIPULLI',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'COLTAUCO',NULL,N'Chile'),
	 (N'COMBARBALA',NULL,N'Chile'),
	 (N'CONCEPCION',NULL,N'Chile'),
	 (N'CONCHALI',NULL,N'Chile'),
	 (N'CONCON',NULL,N'Chile'),
	 (N'CONSTITUCION',NULL,N'Chile'),
	 (N'CONTULMO',NULL,N'Chile'),
	 (N'COPIAPO',NULL,N'Chile'),
	 (N'COQUIMBO',NULL,N'Chile'),
	 (N'CORONEL',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'CORRAL',NULL,N'Chile'),
	 (N'COYHAIQUE',NULL,N'Chile'),
	 (N'CUNCO',NULL,N'Chile'),
	 (N'CURACAUTIN',NULL,N'Chile'),
	 (N'CURACAVI',NULL,N'Chile'),
	 (N'CURACO DE VELEZ',NULL,N'Chile'),
	 (N'CURANILAHUE',NULL,N'Chile'),
	 (N'CURARREHUE',NULL,N'Chile'),
	 (N'CUREPTO',NULL,N'Chile'),
	 (N'CURICO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'DALCAHUE',NULL,N'Chile'),
	 (N'DIEGO DE ALMAGRO',NULL,N'Chile'),
	 (N'DONIHUE',NULL,N'Chile'),
	 (N'EL BOSQUE',NULL,N'Chile'),
	 (N'EL CARMEN',NULL,N'Chile'),
	 (N'EL MONTE',NULL,N'Chile'),
	 (N'EL QUISCO',NULL,N'Chile'),
	 (N'EL TABO',NULL,N'Chile'),
	 (N'EMPEDRADO',NULL,N'Chile'),
	 (N'ERCILLA',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'ESTACION CENTRAL',NULL,N'Chile'),
	 (N'FLORIDA',NULL,N'Chile'),
	 (N'FREIRE',NULL,N'Chile'),
	 (N'FREIRINA',NULL,N'Chile'),
	 (N'FRESIA',NULL,N'Chile'),
	 (N'FRUTILLAR',NULL,N'Chile'),
	 (N'FUTALEUFU',NULL,N'Chile'),
	 (N'FUTRONO',NULL,N'Chile'),
	 (N'GALVARINO',NULL,N'Chile'),
	 (N'GENERAL LAGOS',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'GORBEA',NULL,N'Chile'),
	 (N'GRANEROS',NULL,N'Chile'),
	 (N'GUAITECAS',NULL,N'Chile'),
	 (N'HIJUELAS',NULL,N'Chile'),
	 (N'HUALAIHUE',NULL,N'Chile'),
	 (N'HUALANE',NULL,N'Chile'),
	 (N'HUALPEN',NULL,N'Chile'),
	 (N'HUALQUI',NULL,N'Chile'),
	 (N'HUARA',NULL,N'Chile'),
	 (N'HUASCO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'HUECHURABA',NULL,N'Chile'),
	 (N'ILLAPEL',NULL,N'Chile'),
	 (N'INDEPENDENCIA',NULL,N'Chile'),
	 (N'IQUIQUE',NULL,N'Chile'),
	 (N'ISLA DE MAIPO',NULL,N'Chile'),
	 (N'ISLA DE PASCUA',NULL,N'Chile'),
	 (N'JUAN FERNANDEZ',NULL,N'Chile'),
	 (N'LA CALERA',NULL,N'Chile'),
	 (N'LA CISTERNA',NULL,N'Chile'),
	 (N'LA CRUZ',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'LA ESTRELLA',NULL,N'Chile'),
	 (N'LA FLORIDA',NULL,N'Chile'),
	 (N'LA GRANJA',NULL,N'Chile'),
	 (N'LA HIGUERA',NULL,N'Chile'),
	 (N'LA LIGUA',NULL,N'Chile'),
	 (N'LA PINTANA',NULL,N'Chile'),
	 (N'LA REINA',NULL,N'Chile'),
	 (N'LA SERENA',NULL,N'Chile'),
	 (N'LA UNION',NULL,N'Chile'),
	 (N'LAGO RANCO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'LAGO VERDE',NULL,N'Chile'),
	 (N'LAGUNA BLANCA',NULL,N'Chile'),
	 (N'LAJA',NULL,N'Chile'),
	 (N'LAMPA',NULL,N'Chile'),
	 (N'LANCO',NULL,N'Chile'),
	 (N'LAS CABRAS',NULL,N'Chile'),
	 (N'LAUTARO',NULL,N'Chile'),
	 (N'LEBU',NULL,N'Chile'),
	 (N'LICANTEN',NULL,N'Chile'),
	 (N'LIMACHE',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'LINARES',NULL,N'Chile'),
	 (N'LITUECHE',NULL,N'Chile'),
	 (N'LLANQUIHUE',NULL,N'Chile'),
	 (N'LLAY-LLAY',NULL,N'Chile'),
	 (N'LO BARNECHEA',NULL,N'Chile'),
	 (N'LO ESPEJO',NULL,N'Chile'),
	 (N'LO PRADO',NULL,N'Chile'),
	 (N'LOLOL',NULL,N'Chile'),
	 (N'LONCOCHE',NULL,N'Chile'),
	 (N'LONGAVI',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'LONQUIMAY',NULL,N'Chile'),
	 (N'LOS ALAMOS',NULL,N'Chile'),
	 (N'LOS ANDES',NULL,N'Chile'),
	 (N'LOS ANGELES',NULL,N'Chile'),
	 (N'LOS LAGOS',NULL,N'Chile'),
	 (N'LOS MUERMOS',NULL,N'Chile'),
	 (N'LOS SAUCES',NULL,N'Chile'),
	 (N'LOS VILOS',NULL,N'Chile'),
	 (N'LOTA',NULL,N'Chile'),
	 (N'LUMACO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'MACHALI',NULL,N'Chile'),
	 (N'MACUL',NULL,N'Chile'),
	 (N'MAFIL',NULL,N'Chile'),
	 (N'MAIPU',NULL,N'Chile'),
	 (N'MALLOA',NULL,N'Chile'),
	 (N'MARIA ELENA',NULL,N'Chile'),
	 (N'MARIA PINTO',NULL,N'Chile'),
	 (N'MARIQUINA',NULL,N'Chile'),
	 (N'MAULE',NULL,N'Chile'),
	 (N'MAULLIN',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'MEJILLONES',NULL,N'Chile'),
	 (N'MELIPEUCO',NULL,N'Chile'),
	 (N'MELIPILLA',NULL,N'Chile'),
	 (N'MOLINA',NULL,N'Chile'),
	 (N'MONTE PATRIA',NULL,N'Chile'),
	 (N'MULCHEN',NULL,N'Chile'),
	 (N'NACIMIENTO',NULL,N'Chile'),
	 (N'NANCAGUA',NULL,N'Chile'),
	 (N'NATALES',NULL,N'Chile'),
	 (N'NAVIDAD',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'NEGRETE',NULL,N'Chile'),
	 (N'NINHUE',NULL,N'Chile'),
	 (N'NIQUEN',NULL,N'Chile'),
	 (N'NOGALES',NULL,N'Chile'),
	 (N'NUEVA IMPERIAL',NULL,N'Chile'),
	 (N'NUNOA',NULL,N'Chile'),
	 (N'OHIGGINS',NULL,N'Chile'),
	 (N'OLIVAR',NULL,N'Chile'),
	 (N'OLLAGUE',NULL,N'Chile'),
	 (N'OLMUE',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'OSORNO',NULL,N'Chile'),
	 (N'OVALLE',NULL,N'Chile'),
	 (N'PADRE HURTADO',NULL,N'Chile'),
	 (N'PADRE LAS CASAS',NULL,N'Chile'),
	 (N'PAIHUANO',NULL,N'Chile'),
	 (N'PAILLACO',NULL,N'Chile'),
	 (N'PAINE',NULL,N'Chile'),
	 (N'PALENA',NULL,N'Chile'),
	 (N'PALMILLA',NULL,N'Chile'),
	 (N'PANGUIPULLI',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'PANQUEHUE',NULL,N'Chile'),
	 (N'PAPUDO',NULL,N'Chile'),
	 (N'PAREDONES',NULL,N'Chile'),
	 (N'PARRAL',NULL,N'Chile'),
	 (N'PEDRO AGUIRRE CERDA',NULL,N'Chile'),
	 (N'PELARCO',NULL,N'Chile'),
	 (N'PELLUHUE',NULL,N'Chile'),
	 (N'PEMUCO',NULL,N'Chile'),
	 (N'PENAFLOR',NULL,N'Chile'),
	 (N'PENALOLEN',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'PENCAHUE',NULL,N'Chile'),
	 (N'PENCO',NULL,N'Chile'),
	 (N'PERALILLO',NULL,N'Chile'),
	 (N'PERQUENCO',NULL,N'Chile'),
	 (N'PETORCA',NULL,N'Chile'),
	 (N'PEUMO',NULL,N'Chile'),
	 (N'PICA',NULL,N'Chile'),
	 (N'PICHIDEGUA',NULL,N'Chile'),
	 (N'PICHILEMU',NULL,N'Chile'),
	 (N'PINTO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'PIRQUE',NULL,N'Chile'),
	 (N'PITRUFQUEN',NULL,N'Chile'),
	 (N'PLACILLA',NULL,N'Chile'),
	 (N'PORTEZUELO',NULL,N'Chile'),
	 (N'PORVENIR',NULL,N'Chile'),
	 (N'POZO ALMONTE',NULL,N'Chile'),
	 (N'PRIMAVERA',NULL,N'Chile'),
	 (N'PROVIDENCIA',NULL,N'Chile'),
	 (N'PUCHUNCAVI',NULL,N'Chile'),
	 (N'PUCON',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'PUDAHUEL',NULL,N'Chile'),
	 (N'PUENTE ALTO',NULL,N'Chile'),
	 (N'PUERTO MONTT',NULL,N'Chile'),
	 (N'PUERTO OCTAY',NULL,N'Chile'),
	 (N'PUERTO VARAS',NULL,N'Chile'),
	 (N'PUMANQUE',NULL,N'Chile'),
	 (N'PUNITAQUI',NULL,N'Chile'),
	 (N'PUNTA ARENAS',NULL,N'Chile'),
	 (N'PUQUELDON',NULL,N'Chile'),
	 (N'PUREN',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'PURRANQUE',NULL,N'Chile'),
	 (N'PUTAENDO',NULL,N'Chile'),
	 (N'PUTRE',NULL,N'Chile'),
	 (N'PUYEHUE',NULL,N'Chile'),
	 (N'QUEILEN',NULL,N'Chile'),
	 (N'QUELLON',NULL,N'Chile'),
	 (N'QUEMCHI',NULL,N'Chile'),
	 (N'QUILACO',NULL,N'Chile'),
	 (N'QUILICURA',NULL,N'Chile'),
	 (N'QUILLECO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'QUILLON',NULL,N'Chile'),
	 (N'QUILLOTA',NULL,N'Chile'),
	 (N'QUILPUE',NULL,N'Chile'),
	 (N'QUINCHAO',NULL,N'Chile'),
	 (N'QUINTA DE TILCOCO',NULL,N'Chile'),
	 (N'QUINTA NORMAL',NULL,N'Chile'),
	 (N'QUINTERO',NULL,N'Chile'),
	 (N'QUIRIHUE',NULL,N'Chile'),
	 (N'RANCAGUA',NULL,N'Chile'),
	 (N'RANQUIL',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'RAUCO',NULL,N'Chile'),
	 (N'RECOLETA',NULL,N'Chile'),
	 (N'RENAICO',NULL,N'Chile'),
	 (N'RENCA',NULL,N'Chile'),
	 (N'RENGO',NULL,N'Chile'),
	 (N'REQUINOA',NULL,N'Chile'),
	 (N'RETIRO',NULL,N'Chile'),
	 (N'RINCONADA',NULL,N'Chile'),
	 (N'RIO BUENO',NULL,N'Chile'),
	 (N'RIO CLARO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'RIO HURTADO',NULL,N'Chile'),
	 (N'RIO IBANEZ',NULL,N'Chile'),
	 (N'RIO NEGRO',NULL,N'Chile'),
	 (N'RIO VERDE',NULL,N'Chile'),
	 (N'ROMERAL',NULL,N'Chile'),
	 (N'SAAVEDRA',NULL,N'Chile'),
	 (N'SAGRADA FAMILIA',NULL,N'Chile'),
	 (N'SALAMANCA',NULL,N'Chile'),
	 (N'SAN ANTONIO',NULL,N'Chile'),
	 (N'SAN BERNARDO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'SAN CARLOS',NULL,N'Chile'),
	 (N'SAN CLEMENTE',NULL,N'Chile'),
	 (N'SAN ESTEBAN',NULL,N'Chile'),
	 (N'SAN FABIAN',NULL,N'Chile'),
	 (N'SAN FELIPE',NULL,N'Chile'),
	 (N'SAN FERNANDO',NULL,N'Chile'),
	 (N'SAN FRANCISCO DE MOSTAZAL',NULL,N'Chile'),
	 (N'SAN GREGORIO',NULL,N'Chile'),
	 (N'SAN IGNACIO',NULL,N'Chile'),
	 (N'SAN JAVIER',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'SAN JOAQUIN',NULL,N'Chile'),
	 (N'SAN JOSE DE MAIPO',NULL,N'Chile'),
	 (N'SAN JUAN DE LA COSTA',NULL,N'Chile'),
	 (N'SAN MIGUEL',NULL,N'Chile'),
	 (N'SAN NICOLAS',NULL,N'Chile'),
	 (N'SAN PABLO',NULL,N'Chile'),
	 (N'SAN PEDRO',NULL,N'Chile'),
	 (N'SAN PEDRO DE ATACAMA',NULL,N'Chile'),
	 (N'SAN PEDRO DE LA PAZ',NULL,N'Chile'),
	 (N'SAN RAFAEL',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'SAN RAMON',NULL,N'Chile'),
	 (N'SAN ROSENDO',NULL,N'Chile'),
	 (N'SAN VICENTE',NULL,N'Chile'),
	 (N'SANTA BARBARA',NULL,N'Chile'),
	 (N'SANTA CRUZ',NULL,N'Chile'),
	 (N'SANTA JUANA',NULL,N'Chile'),
	 (N'SANTA MARIA',NULL,N'Chile'),
	 (N'SANTIAGO',NULL,N'Chile'),
	 (N'SANTIAGO OESTE',NULL,N'Chile'),
	 (N'SANTIAGO SUR',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'SANTO DOMINGO',NULL,N'Chile'),
	 (N'SIERRA GORDA',NULL,N'Chile'),
	 (N'TALAGANTE',NULL,N'Chile'),
	 (N'TALCA',NULL,N'Chile'),
	 (N'TALCAHUANO',NULL,N'Chile'),
	 (N'TALTAL',NULL,N'Chile'),
	 (N'TEMUCO',NULL,N'Chile'),
	 (N'TENO',NULL,N'Chile'),
	 (N'TEODORO SCHMIDT',NULL,N'Chile'),
	 (N'TIERRA AMARILLA',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'TIL-TIL',NULL,N'Chile'),
	 (N'TIMAUKEL',NULL,N'Chile'),
	 (N'TIRUA',NULL,N'Chile'),
	 (N'TOCOPILLA',NULL,N'Chile'),
	 (N'TOLTEN',NULL,N'Chile'),
	 (N'TOME',NULL,N'Chile'),
	 (N'TORRES DEL PAINE',NULL,N'Chile'),
	 (N'TORTEL',NULL,N'Chile'),
	 (N'TRAIGUEN',NULL,N'Chile'),
	 (N'TREHUACO',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'TUCAPEL',NULL,N'Chile'),
	 (N'VALDIVIA',NULL,N'Chile'),
	 (N'VALLENAR',NULL,N'Chile'),
	 (N'VALPARAISO',NULL,N'Chile'),
	 (N'VICHUQUEN',NULL,N'Chile'),
	 (N'VICTORIA',NULL,N'Chile'),
	 (N'VICUNA',NULL,N'Chile'),
	 (N'VILCUN',NULL,N'Chile'),
	 (N'VILLA ALEGRE',NULL,N'Chile'),
	 (N'VILLA ALEMANA',NULL,N'Chile');
INSERT INTO [Blui-Local].dbo.Comuna (name,region,country) VALUES
	 (N'VILLARRICA',NULL,N'Chile'),
	 (N'VITACURA',NULL,N'Chile'),
	 (N'YERBAS BUENAS',NULL,N'Chile'),
	 (N'YUMBEL',NULL,N'Chile'),
	 (N'YUNGAY',NULL,N'Chile'),
	 (N'ZAPALLAR',NULL,N'Chile');
